require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

deployment_target = Gem::Version.new('12.4')

platform :ios, deployment_target
install! 'cocoapods', :deterministic_uuids => false

target 'RnTodoAuth' do
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    # Upcoming versions of React Native may rely on get_default_flags(), but
    # we make it explicit here to aid in the React Native upgrade process.
    :hermes_enabled => true,
    :fabric_enabled => flags[:fabric_enabled],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    :flipper_configuration => FlipperConfiguration.enabled,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'RnTodoAuthTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      # Set `mac_catalyst_enabled` to `true` in order to apply patches
      # necessary for Mac Catalyst builds
      :mac_catalyst_enabled => false
    )
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
    
    # https://stackoverflow.com/questions/72846698/react-native-ios-0-69-1-build-failed-when-creating-new-project
    # target -> https://www.rubydoc.info/gems/xcodeproj/Xcodeproj/Project/Object/PBXNativeTarget
    installer.pods_project.targets.each do |target|
      case target.name
      # Ignore RCT-Folly because it only works with 9.0 as a deployment target
      when 'RCT-Folly'
        next
      else
        # Explicitly set pods deployment target for each build config to app deployment target
        target.build_configurations.each do |config|
          current_pod_target = config.build_settings['IPHONEOS_DEPLOYMENT_TARGET']
          pod_ios_deployment_target = Gem::Version.new(current_pod_target)
          if pod_ios_deployment_target <= deployment_target
            config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
          end
        end
      end
    end
  end
end
